modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="clay_wars"
version="${mod_version}"
displayName="Clay Wars"
description='''Simulador de civilizaciones en miniatura: soldaditos rojos y azules que recolectan, comen, crecen y (pronto) guerrean.'''

[[dependencies.clay_wars]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.clay_wars]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
